export const ANIMALS: string[] = [
  "Octopuses have three hearts and blue blood.",
  "A group of flamingos is called a flamboyance.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "Cows have best friends and get stressed when separated.",
  "A shrimp's heart is in its head.",
  "Bananas are berries, but strawberries aren't.",
  "Sharks existed before trees.",
  "Butterflies taste with their feet.",
  "An octopus has nine brains — one central and one per arm.",
  "Trees can communicate and share nutrients through underground fungal networks.",
  "Hummingbirds are the only birds that can fly backwards.",
  "A snail can sleep for up to three years.",
  "Elephants are one of the few animals that can recognize themselves in a mirror.",
  "Crows can remember human faces for years — and hold grudges.",
  "Honeybees communicate the location of flowers by dancing.",
  "A blue whale's heart is the size of a small car.",
  "Penguins propose with pebbles — males gift stones to potential mates.",
  "Wombat poop is cube-shaped.",
  "Dolphins call each other by name using signature whistles.",
  "Tardigrades can survive the vacuum of space.",
  "A cheetah accelerates faster than most sports cars.",
  "Ants never sleep the way we do — they take hundreds of tiny naps a day.",
  "Some jellyfish are biologically immortal — they can revert to their juvenile form.",
  "Goats have rectangular pupils, giving them almost 340° vision.",
  "Polar bear skin is black; their fur is transparent, not white.",
  "Owls can't move their eyes — that's why they rotate their heads up to 270°.",
  "The mantis shrimp punches with the acceleration of a .22 caliber bullet.",
  "Koalas sleep up to 22 hours a day.",
  "Giraffes have the same number of neck vertebrae as humans: seven.",
  "Starfish have no brain and no blood.",
  "A hummingbird weighs less than a coin.",
  "Cats can't taste sweetness.",
  "Rats laugh when tickled — at frequencies too high for humans to hear.",
  "The axolotl can regrow limbs, spinal cord, heart tissue, and parts of its brain.",
  "Emperor penguin dads incubate the egg on their feet through the Antarctic winter.",
  "Horses can't breathe through their mouths.",
  "A single oak tree can host over 2,000 different species.",
  "Sloths can hold their breath longer than dolphins — up to 40 minutes.",
  "Bees can recognize human faces.",
  "The fingerprints of a koala are almost indistinguishable from a human's.",
  "Flamingos are born grey — shrimp and algae pigments turn them pink.",
  "Squirrels plant thousands of trees each year simply by forgetting where they buried nuts.",
  "The heart of a hibernating hedgehog drops from 190 to about 20 beats per minute.",
  "Some bamboo species grow almost a meter per day.",
  "Chameleons change color mostly to communicate mood, not to camouflage.",
  "An albatross can glide for hours without flapping its wings once.",
  "Seahorse males carry and give birth to the young.",
  "Africa's Sahara was green savanna with lakes just 6,000 years ago.",
  "Orcas are actually the largest species of dolphin.",
  "A woodpecker's tongue wraps around its skull to cushion its brain while drumming.",
];
