export const HEALTH: string[] = [
  "You blink about 66% less while staring at a screen — that's why your eyes feel dry.",
  "The 20-20-20 rule exists because your eye's focusing muscle never rests at close range.",
  "Your brain is ~75% water. Just 2% dehydration measurably drops concentration.",
  "An hour of sitting reduces blood flow to the brain. A 2-minute walk restores it.",
  "Your spine is about 1 cm shorter in the evening than in the morning.",
  "Looking at something far away fully relaxes the ciliary muscle inside your eye.",
  "A 5-minute walk every hour offsets most of the metabolic harm of sitting.",
  "Your head weighs ~5 kg upright — but pulls like 27 kg on your neck at a 60° phone tilt.",
  "Drinking water improves reaction time within about 15 minutes.",
  "Standing burns roughly 50 more calories per hour than sitting.",
  "Walking boosts creative thinking by around 60% — Stanford measured it.",
  "Muscles begin stiffening after just 30 minutes of stillness.",
  "Office workers spend up to 1,700 hours a year looking at screens.",
  "Good hydration keeps the discs between your vertebrae cushioned — they're mostly water.",
  "Natural light exposure during breaks helps regulate your sleep cycle.",
  "Slouching can reduce lung capacity by up to 30%.",
  "Your eyes make about three rapid movements per second — over 100,000 saccades a day.",
  "Deep breathing for 60 seconds measurably lowers heart rate and blood pressure.",
  "Stretching improves blood flow to muscles in under 30 seconds.",
  "Your cornea has no blood supply — it takes oxygen directly from the air.",
  "Laughing increases blood flow by around 20%, similar to light exercise.",
  "Your body has about 37 trillion cells, most replaced many times over your lifetime.",
  "Bone is, gram for gram, stronger than steel.",
  "The human eye can distinguish roughly 10 million colors.",
  "Regular short walks improve insulin sensitivity within days.",
  "Your heart beats about 100,000 times a day.",
  "Tears produced while blinking keep your cornea fed — no blinking, no nutrition.",
  "Sitting cross-legged for long periods can temporarily compress the peroneal nerve — that's the 'foot asleep' feeling.",
  "Your resting brain still consumes about a fifth of your daily energy.",
  "Wrists have 8 small bones each — repetitive strain inflames the tunnel they form.",
  "Looking at screens up close all day is linked to rising nearsightedness worldwide.",
  "Your blood is about 90% water — hydration literally keeps it flowing.",
  "A good stretch triggers your muscles' relaxation reflex within about 20 seconds.",
  "Humans are the only great apes with a protruding chin.",
  "Caffeine takes about 20 minutes to kick in — a coffee then a 15-minute nap stacks both.",
  "Your body temperature naturally dips mid-afternoon — that slump isn't just lunch.",
  "Shoulder rolls increase blood flow to the neck muscles that hold up your head all day.",
  "Most adults need 7–9 hours of sleep; less than 6 measurably impairs reaction time.",
  "Standing up straight can measurably improve mood and energy levels.",
  "The average person walks about 120,000 km in a lifetime — three times around Earth.",
  "Eye strain doesn't damage your eyes permanently, but it does wreck your focus.",
  "Your lungs contain around 480 million alveoli — spread out, near a tennis court in area.",
  "Fidgeting can burn a few hundred extra calories a day.",
  "Skin is your largest organ — around 2 square meters of it.",
  "Hydrated joints move more smoothly: cartilage is up to 80% water.",
  "A brisk 10-minute walk can boost energy for up to two hours.",
  "Your Achilles tendon can take loads of over 10 times your body weight.",
  "Blue light suppresses melatonin — screens before bed delay your sleep clock.",
  "Muscles account for roughly 40% of your body weight.",
  "Cold water on your wrists cools you fast — blood vessels run close to the skin there.",
];
