export const HISTORY: string[] = [
  "Oxford University is older than the Aztec Empire.",
  "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
  "The fax machine was invented in 1843 — decades before the telephone.",
  "Woolly mammoths were still alive while the Egyptian pyramids were being built.",
  "The shortest war in history, between Britain and Zanzibar in 1896, lasted under 40 minutes.",
  "Ancient Romans used crushed mouse brains as toothpaste.",
  "The Eiffel Tower was meant to be temporary — built on a 20-year permit.",
  "Nintendo was founded in 1889 — as a playing-card company.",
  "The Great Fire of London in 1666 officially recorded only six deaths.",
  "Ketchup was sold as medicine in the 1830s.",
  "Ancient Egyptians used moldy bread on wounds — millennia before penicillin was isolated.",
  "The last execution by guillotine in France happened in 1977 — the year Star Wars premiered.",
  "Vikings reached North America about 500 years before Columbus.",
  "In ancient Rome, urine was collected and taxed — it was used to wash clothes.",
  "The University of Bologna has been teaching since 1088.",
  "Napoleon wasn't short — he was about average height for his time; British propaganda shrank him.",
  "Tea bags were invented by accident: samples shipped in silk pouches got dunked whole.",
  "The Colosseum could reportedly be flooded for staged naval battles.",
  "The 1904 Olympic marathon winner was driven part of the route in a car — then disqualified.",
  "London's Underground opened in 1863 — trains were steam-powered.",
  "The Hundred Years' War lasted 116 years.",
  "Roman concrete grows stronger in seawater — modern engineers study the recipe.",
  "The Leaning Tower of Pisa started tilting during construction — in the 1170s.",
  "Genghis Khan's empire became the largest contiguous land empire in history.",
  "The first vending machine, in 1st-century Egypt, dispensed holy water for a coin.",
  "Before alarm clocks, 'knocker-uppers' were hired to tap on windows with long poles.",
  "The Ancient Greeks had a working steam engine — the aeolipile — and used it as a toy.",
  "The Berlin Wall stood for 28 years; it has now been gone longer than it stood.",
  "In medieval Europe, animals could be put on trial — pigs were actual defendants.",
  "The Statue of Liberty was originally shiny copper brown; the green patina took decades.",
  "Anne Frank, Martin Luther King Jr., and Barbara Walters were all born in 1929.",
  "The ancient Olympics ran for nearly 12 centuries before being abolished in 393 AD.",
  "Persia's Cyrus Cylinder from 539 BC is often called the first charter of human rights.",
  "Harvard was founded before calculus was invented.",
  "The Ottoman Empire still existed the last time the Chicago Cubs had won a World Series (1908).",
  "The Pony Express lasted only 18 months before the telegraph made it obsolete.",
  "Ancient Egyptians had a pregnancy test using wheat and barley seeds — and it partly worked.",
  "In 1919, a wave of molasses flooded Boston streets at 55 km/h, killing 21 people.",
  "The Mona Lisa was stolen from the Louvre in 1911 — the theft made it world-famous.",
  "The first traffic light, installed in London in 1868, exploded a month later.",
  "The Roman Empire and the Han dynasty knew of each other and traded along the Silk Road.",
  "France was still executing by guillotine when Microsoft was founded.",
  "The Great Wall of China took around 2,000 years to build across many dynasties.",
  "Julius Caesar was kidnapped by pirates — and demanded they raise his ransom.",
  "Saudi Arabia imports camels — many from Australia.",
  "Pineapples were so rare in 1700s Europe that people rented them as party decorations.",
  "The first photograph of a person (1838) captured a man having his shoes shined in Paris.",
  "The Titanic's distress calls used Morse code — the SOS signal was still fairly new.",
  "The Aztecs used cacao beans as currency.",
  "Ancient Babylonians did trigonometry a thousand years before Pythagoras.",
];
