export const JOKES: string[] = [
  "I told my computer I needed a break. It said: no problem — I'll go to sleep too.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "A SQL query walks into a bar, approaches two tables and asks: mind if I join you?",
  "There are 10 types of people: those who understand binary and those who don't.",
  "99 little bugs in the code. Take one down, patch it around — 127 little bugs in the code.",
  "Why did the developer go broke? He used up all his cache.",
  "!false — it's funny because it's true.",
  "A programmer's partner says: buy a loaf of bread, and if they have eggs, buy a dozen. He returns with 12 loaves.",
  "Hardware: the part of the computer you can kick.",
  "My code doesn't have bugs. It has undocumented features.",
  "Why do Java developers wear glasses? Because they don't C#.",
  "To understand recursion, you must first understand recursion.",
  "\"It works on my machine\" — famous last words.",
  "Debugging: being the detective in a crime movie where you are also the murderer.",
  "The best thing about a Boolean: even if you're wrong, you're only off by a bit.",
  "A UDP packet walks into a bar. Nobody acknowledges it.",
  "I would tell you a joke about DNS, but it might take 24 hours to reach you.",
  "Programming is 10% writing code and 90% figuring out why it doesn't work.",
  "There's no place like 127.0.0.1.",
  "I changed my password to \"incorrect\", so my computer reminds me when I forget it.",
  "Real programmers count from 0.",
  "An SEO expert walks into a bar, bars, pub, tavern, drinks, beer, alcohol...",
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
  "Software and cathedrals: first we build them, then we pray.",
  "The two hardest problems in CS: cache invalidation, naming things, and off-by-one errors.",
  "Documentation is like a love letter you write to your future self.",
  "Deleted code is debugged code.",
  "Artificial intelligence is no match for natural stupidity.",
  "A TCP packet walks into a bar and says: I'd like a beer. Bartender: you'd like a beer? Packet: yes, I'd like a beer.",
  "Knock knock. Who's there? ...long pause... Java.",
  "Why did the programmer quit his job? Because he didn't get arrays.",
  "In order to understand what a while loop does, keep reading this sentence until you understand it.",
  "Copy-and-paste was programmed by programmers for programmers actually.",
  "A byte walks into a bar looking miserable. Bartender: what's wrong? Byte: parity error. Bartender: yeah, you look a bit off.",
  "How many programmers does it take to change a light bulb? None — that's a hardware problem.",
  "Front-end developers do it with <style>.",
  "I've got a really good UDP joke to tell you, but I don't know if you'll get it.",
  "Why don't programmers like nature? It has too many bugs and no debugger.",
  "The programmer got stuck in the shower because the shampoo said: lather, rinse, repeat.",
  "Algorithm: a word used by programmers when they don't want to explain what they did.",
  "My software never has bugs — it just develops random features.",
  "CAPS LOCK: preventing login since 1980.",
  "If at first you don't succeed, call it version 1.0.",
  "The cloud is just someone else's computer.",
  "Programmer: a machine that turns coffee into code.",
  "Why did the functions stop calling each other? They had too many arguments.",
  "Git happens.",
  "Whitespace is not nothing — ask any Python developer.",
  "A user interface is like a joke: if you have to explain it, it's not that good.",
  "The best performance improvement is when the code goes from not working to working.",
];
