export const MATHS: string[] = [
  "There are infinitely many primes — Euclid proved it around 300 BC, and the proof still fits in a paragraph.",
  "Fermat's Last Theorem sat unproven for 358 years until Andrew Wiles cracked it in 1994.",
  "The Collatz conjecture is simple enough for a child to state and still unsolved after 90 years.",
  "Euler's identity links e, i, π, 1 and 0 in one line: e^(iπ) + 1 = 0.",
  "There are more real numbers between 0 and 1 than there are whole numbers in total.",
  "The four colour theorem was the first major proof to rely on a computer, in 1976.",
  "π has been computed to over 100 trillion digits, yet 39 digits suffice to measure the observable universe to atomic precision.",
  "Gödel proved that any consistent system rich enough for arithmetic contains truths it cannot prove.",
  "A Möbius strip has only one side and one edge — cut it down the middle and it stays in one piece.",
  "The Riemann hypothesis, unsolved since 1859, carries a $1,000,000 prize.",
  "Six of the seven Millennium Prize Problems are still open; only the Poincaré conjecture has fallen.",
  "Grigori Perelman solved the Poincaré conjecture in 2003 and turned down both the $1M prize and the Fields Medal.",
  "The Banach–Tarski paradox says a solid ball can be split and reassembled into two identical balls.",
  "0.999... exactly equals 1 — not approximately, exactly.",
  "The golden ratio φ appears in sunflower seed spirals, pinecones and nautilus shells.",
  "Fibonacci numbers divided by their predecessors converge on the golden ratio.",
  "Any map needs at most four colours so that no two bordering regions share one.",
  "The Pythagorean theorem has over 350 known distinct proofs, one by a future US president.",
  "There are exactly five Platonic solids — Euclid proved no sixth can exist.",
  "Graham's number is so large that writing its digits would exceed the space in the observable universe.",
  "A googol is 10^100; a googolplex is 10 raised to a googol, and cannot be written out in this universe.",
  "The Monty Hall problem: switching doors doubles your odds from 1/3 to 2/3.",
  "In a room of 23 people, there's a better-than-even chance two share a birthday.",
  "Prime numbers thin out as you climb, but never run out — gaps between them can be arbitrarily large.",
  "Twin primes like 11 and 13 are conjectured to be infinite, but nobody has proved it.",
  "The largest known prime has over 41 million digits and was found in 2024.",
  "Zero was invented as a number relatively late — India formalized it around the 7th century.",
  "Negative numbers were dismissed as 'absurd' by European mathematicians well into the 1600s.",
  "The number e ≈ 2.71828 arises naturally from compound interest computed continuously.",
  "Chaos theory's butterfly effect: tiny changes in initial conditions produce wildly different outcomes.",
  "A Klein bottle has no inside or outside — and can't exist without self-intersecting in 3D.",
  "Cantor proved some infinities are strictly larger than others, and was ridiculed for it.",
  "The halting problem is provably unsolvable — no algorithm can decide if any program will stop.",
  "Hilbert's Hotel has infinite rooms, all full, and can still take infinitely many new guests.",
  "The ancient Greeks proved √2 is irrational — legend says the discoverer was drowned for it.",
  "Modern encryption rests on the fact that multiplying huge primes is easy but factoring the result is hard.",
  "A sphere can be turned inside out smoothly without creasing — it's called sphere eversion.",
  "The Mandelbrot set's boundary has infinite detail: zoom forever and new structure keeps appearing.",
  "Fractals have dimensions that aren't whole numbers — Britain's coastline is roughly 1.25-dimensional.",
  "Benford's law: in real-world data, the leading digit is 1 about 30% of the time, not 11%.",
  "Auditors use Benford's law to detect fabricated financial figures.",
  "The Traveling Salesman Problem for just 20 cities has more routes than atoms in a teaspoon of water.",
  "P vs NP asks whether every quickly-checkable problem is also quickly solvable — still open.",
  "Euler solved the Seven Bridges of Königsberg in 1736 and invented graph theory doing it.",
  "Any two people on Earth are connected by about six intermediate acquaintances on average.",
  "Gauss reportedly summed 1 to 100 in seconds as a schoolboy by pairing terms: 50 × 101 = 5050.",
  "The Fields Medal is awarded only to mathematicians aged 40 or under.",
  "Maryam Mirzakhani became the first woman to win the Fields Medal in 2014.",
  "The number 1729 is the smallest expressible as a sum of two cubes in two ways — Ramanujan spotted it instantly.",
  "Ramanujan filled notebooks with thousands of theorems, many unproven for decades after his death.",
  "A perfect number equals the sum of its divisors: 6 = 1 + 2 + 3. Only 51 are known.",
  "Nobody knows whether any odd perfect number exists — the search has run for over 2,000 years.",
  "The Goldbach conjecture — every even number above 2 is the sum of two primes — is verified to 4 × 10^18 but unproven.",
  "Shuffle a deck properly and you've almost certainly created an order no deck has ever been in.",
  "There are 52! ways to order a deck — roughly 8 × 10^67, more than atoms in our galaxy.",
  "Non-Euclidean geometry seemed useless until Einstein used it to describe curved spacetime.",
  "The Fourier transform breaks any signal into pure sine waves — it powers JPEG, MP3 and MRI.",
  "Zeno's paradox: to cross a room you must first cross half, then half again — yet you still arrive.",
  "An infinite series can converge to a finite number: 1/2 + 1/4 + 1/8 + ... = 1.",
  "The harmonic series 1 + 1/2 + 1/3 + ... grows without bound, just extremely slowly.",
];
