export const MIND: string[] = [
  "Your brain uses about 20% of your body's energy while being 2% of its weight.",
  "Short breaks during learning improve retention — your brain replays new skills at rest.",
  "The brain can't actually multitask — it switches rapidly, losing time with every switch.",
  "After an interruption it takes about 23 minutes to fully refocus.",
  "Your brain generates roughly 12–25 watts — enough to power a dim LED bulb.",
  "Naps as short as 10 minutes measurably improve alertness.",
  "Handwriting notes improves memory more than typing them.",
  "The 'doorway effect' is real: walking through a doorway makes you forget why you came.",
  "Writing tasks down reduces anxiety — your brain treats lists as offloaded memory.",
  "Dopamine spikes in anticipation of a reward, not just on receiving it.",
  "Your brain has about 86 billion neurons, each with thousands of connections.",
  "Memories change slightly every time you recall them.",
  "The Zeigarnik effect: unfinished tasks occupy your mind more than completed ones.",
  "Boredom sparks creativity — your brain's default mode network lights up when idle.",
  "You make about 35,000 decisions every day.",
  "Willpower behaves like a muscle: it fatigues with use and recovers with rest.",
  "Chewing gum can temporarily increase alertness and focus.",
  "The brain processes images in as little as 13 milliseconds.",
  "Smell is the sense most directly wired to memory.",
  "Your attention span works in cycles — focus naturally dips roughly every 90 minutes.",
  "Learning a new skill physically rewires your brain — at any age.",
  "The mere-exposure effect: you like things more simply because they're familiar.",
  "Sleep is when your brain consolidates the day's learning into long-term memory.",
  "The tip-of-the-tongue feeling happens in every language and every culture.",
  "Your peripheral vision is mostly colorblind — the brain fills the color in.",
  "Placebos can work even when you know they're placebos.",
  "Bilingual brains show delayed onset of dementia symptoms — by about 4 years on average.",
  "Deadlines sharpen focus: mild time pressure boosts performance, panic destroys it.",
  "You can't tickle yourself — your brain predicts and cancels the sensation.",
  "Stress shrinks the hippocampus, the brain's memory hub — rest regrows connections.",
  "Reading fiction measurably improves empathy.",
  "The brain names things fast: you recognize a face in about a tenth of a second.",
  "Music you love triggers the same reward circuits as food.",
  "Your brain keeps developing until about age 25 — the planning regions mature last.",
  "Mind-wandering fills up to half of your waking thoughts.",
  "Exercise grows new neurons in the hippocampus — cardio is memory training.",
  "The spacing effect: reviewing material over days beats cramming, every time.",
  "Talking to yourself out loud improves task focus — instructions work better spoken.",
  "Blue-enriched light in the morning boosts alertness; the same light at night ruins sleep.",
  "Your brain burns extra glucose when concentrating — hard thinking is real work.",
  "People remember the start and end of an experience best — the serial position effect.",
  "Doodling during meetings can improve recall of what was said.",
  "Gratitude journaling measurably improves mood within weeks.",
  "Your inner voice reads at about the same speed you speak.",
  "The brain treats social rejection with the same circuits as physical pain.",
  "Confidence in a memory says little about its accuracy.",
  "Two-thirds of people experience 'earworms' — songs stuck on mental repeat.",
  "Making a decision, any decision, reduces anxiety — uncertainty is the stressor.",
  "Green spaces lower cortisol: even photos of nature calm the stress response.",
  "The brain is more creative when slightly tired — off-peak hours favor insight.",
];
