export const OCEANS: string[] = [
  "The ocean covers about 71% of Earth's surface and holds 97% of its water.",
  "More than 80% of the ocean is still unmapped and unexplored.",
  "The Mariana Trench's deepest point is nearly 11 km down — Everest would fit with 2 km to spare.",
  "The ocean produces over half of the oxygen you breathe, mostly via plankton.",
  "The Great Barrier Reef is the largest living structure on Earth — visible from space.",
  "The blue whale, the largest animal ever known, lives in the ocean today.",
  "At its deepest points, ocean pressure exceeds 1,000 times that at sea level.",
  "The Mid-Ocean Ridge is Earth's longest mountain range — about 65,000 km, nearly all underwater.",
  "Around 94% of Earth's living species exist in the oceans.",
  "The Pacific is wider than the Moon — over 19,000 km at its widest.",
  "Ocean currents move heat around the planet like a global conveyor belt.",
  "The Gulf Stream carries more water than all the world's rivers combined.",
  "Sunlight can't reach below about 1,000 meters — most of the ocean is permanently dark.",
  "Most tsunamis pass unnoticed under ships at sea — they only rear up near shore.",
  "There are more historic artifacts under the sea than in all the world's museums.",
  "The ocean's average depth is about 3.7 km.",
  "Half of the United States lies beneath the ocean — counting its territorial waters.",
  "Sound travels almost five times faster in seawater than in air.",
  "Whale songs can travel hundreds of kilometers underwater.",
  "The deep sea hosts hydrothermal vents hotter than 400 °C where life still thrives.",
  "Giant kelp can grow up to 60 cm in a single day.",
  "The anglerfish lures prey with a glowing rod — deep-sea bioluminescence is everywhere.",
  "About 90% of ocean life glows: bioluminescence is the rule down deep, not the exception.",
  "Coral reefs support a quarter of all marine species on under 1% of the ocean floor.",
  "Sea level has risen about 20 cm since 1900.",
  "The ocean absorbs about a quarter of the CO₂ humans emit each year.",
  "Antarctica's ice holds enough water to raise sea levels by roughly 58 meters.",
  "Some deep-sea creatures live their whole lives without ever seeing sunlight.",
  "Octopuses can squeeze through any gap larger than their beak — their only hard part.",
  "A single drop of seawater can contain millions of bacteria and viruses.",
  "The Dead Sea is so salty you float effortlessly — nearly 10 times saltier than the ocean.",
  "The Atlantic Ocean grows about 4 cm wider every year.",
  "Sperm whales dive over 2 km deep and hold their breath for up to 90 minutes.",
  "Sea turtles navigate thousands of kilometers using Earth's magnetic field.",
  "The giant squid has the largest eyes in the animal kingdom — dinner-plate sized.",
  "The Challenger Deep has been visited by fewer people than the Moon.",
  "Icebergs are freshwater — ancient snow, not frozen seawater.",
  "The Sargasso Sea is the only sea with no coastline — bounded entirely by currents.",
  "Eels from Europe and America both spawn in the Sargasso Sea, then migrate back.",
  "Waves can travel across an entire ocean basin without losing much energy.",
  "The Mediterranean nearly dried up completely about 5.5 million years ago.",
  "Underwater waterfalls exist — the Denmark Strait cataract drops 3.5 km.",
  "The ocean floor is dotted with more than a million estimated seamounts.",
  "The mantis shrimp sees more color channels than any known animal — 16 photoreceptor types.",
  "Dolphins sleep with one half of their brain at a time, keeping one eye open.",
  "Some whale falls feed deep-sea ecosystems for decades after the whale dies.",
  "The hadal zone — below 6 km — is named after Hades, the Greek underworld.",
  "The world's longest animal may be the bootlace worm — specimens near 55 meters washed ashore.",
  "The immortal jellyfish, found in the ocean, can age backwards.",
  "Plastic has been found in the deepest ocean trench — nowhere is untouched.",
];
