export const SCIENCE: string[] = [
  "A day on Venus is longer than its year.",
  "Sunlight takes about 8 minutes and 20 seconds to reach Earth.",
  "Neutron stars are so dense a teaspoon would weigh billions of tons.",
  "Hot water can freeze faster than cold water — the Mpemba effect.",
  "There are more stars in the universe than grains of sand on all Earth's beaches.",
  "Honey never spoils — edible honey has been found in 3,000-year-old Egyptian tombs.",
  "Lightning is about five times hotter than the surface of the Sun.",
  "Water expands about 9% when it freezes — that's why ice floats.",
  "The Moon drifts about 3.8 cm farther from Earth every year.",
  "Helium is the only element that can't be frozen solid at normal pressure.",
  "One million Earths could fit inside the Sun.",
  "Sound travels about four times faster in water than in air.",
  "Jupiter's Great Red Spot is a storm bigger than Earth that has raged for centuries.",
  "Diamonds and pencil lead are both pure carbon — just arranged differently.",
  "The universe is about 13.8 billion years old.",
  "You are made of stardust — most elements in your body formed inside stars.",
  "A bolt of lightning contains enough energy to toast about 100,000 slices of bread.",
  "Saturn is so light it would float in a big enough bathtub.",
  "Absolute zero, −273.15 °C, is the coldest temperature physically possible.",
  "The Sun loses about 4 million tons of mass every second, converted to light.",
  "Glass is neither a normal solid nor a liquid — it's an amorphous solid.",
  "Octillions of neutrinos from the Sun pass through your body every second, touching nothing.",
  "Mercury and Venus are the only planets with no moons.",
  "The Pacific Ocean is shrinking a few centimeters per year; the Atlantic is growing.",
  "Earth's core is about as hot as the Sun's surface — roughly 5,500 °C.",
  "A full NASA space suit costs millions of dollars — most of it for the gloves and life support.",
  "Rain on Titan, Saturn's moon, is liquid methane.",
  "Light from the Andromeda galaxy left it 2.5 million years ago — before humans existed.",
  "Hydrogen makes up about 75% of the normal matter in the universe.",
  "Bananas are slightly radioactive — they're rich in potassium-40.",
  "The Eiffel Tower grows about 15 cm taller in summer as the iron expands.",
  "In space no one can hear you scream: sound needs a medium to travel.",
  "One year on Neptune lasts about 165 Earth years.",
  "Air is mostly nitrogen — oxygen is only about 21% of every breath.",
  "Water is the only common substance found naturally as solid, liquid, and gas on Earth.",
  "Astronauts grow up to 5 cm taller in orbit — their spines decompress.",
  "The Milky Way and Andromeda will collide in about 4.5 billion years.",
  "Atoms are 99.9999999% empty space — squeeze it out and humanity fits in a sugar cube.",
  "Mars has the tallest volcano in the solar system: Olympus Mons, nearly three times Everest.",
  "Gold is forged in colliding neutron stars — every ring is cosmic debris.",
  "Sea level pressure means about 1 kg of air pushes on every square centimeter of you.",
  "The observable universe holds an estimated two trillion galaxies.",
  "GPS satellites must correct for relativity — their clocks tick faster than yours.",
  "A photon can take 100,000 years to escape the Sun's core, then 8 minutes to reach Earth.",
  "The coldest known place in the universe is a lab on Earth — physicists beat deep space.",
  "Venus spins backwards: its Sun rises in the west.",
  "Your body replaces its outer skin layer roughly every month.",
  "Antarctica is the largest desert on Earth — deserts are defined by precipitation, not heat.",
  "E = mc² means one gram of matter holds the energy of about 21 kilotons of TNT.",
  "Oxygen gas is colorless, but liquid oxygen is pale blue.",
];
