export const TECH: string[] = [
  "The first computer bug was an actual moth, found in a Harvard Mark II relay in 1947.",
  "The first 1 GB hard drive (1980) weighed over 200 kg and cost $40,000.",
  "Around 90% of the world's data was created in just the last few years.",
  "The QWERTY layout was designed in the 1870s to reduce typewriter jams.",
  "The first website, info.cern.ch, is still online.",
  "Email predates the World Wide Web by about 20 years.",
  "The Apollo 11 guidance computer had less memory than a musical greeting card.",
  "CAPTCHA stands for Completely Automated Public Turing test to tell Computers and Humans Apart.",
  "The @ symbol was chosen for email in 1971 because it was unlikely to appear in names.",
  "Wi-Fi doesn't stand for anything — it's a made-up brand name.",
  "The first computer mouse, built in the 1960s, was made of wood.",
  "The first camera phone photo was taken in 1997 — of a newborn baby.",
  "More than half of all internet traffic comes from bots and automated tools.",
  "The save icon is a floppy disk — an object many users have never held.",
  "Nokia was founded as a paper mill in 1865.",
  "The first computer programmer was Ada Lovelace, in the 1840s — before computers existed.",
  "The word 'robot' comes from the Czech 'robota', meaning forced labor.",
  "Amazon started as an online bookstore in 1994.",
  "The first domain name ever registered was symbolics.com, in March 1985.",
  "The entire internet weighs about as much as a strawberry — counting electron energy in transit.",
  "YouTube was originally designed as a video dating site.",
  "The Firefox logo animal isn't a fox — a 'firefox' is a red panda.",
  "About 300 hours of video are uploaded to YouTube every minute.",
  "The first text message ever sent (1992) was 'Merry Christmas'.",
  "Bluetooth is named after a 10th-century Danish king, Harald Bluetooth.",
  "The Windows 95 startup sound was composed by Brian Eno — on a Mac.",
  "In 1999 the average webpage was about 30 KB; today it's often over 2 MB.",
  "COBOL code from the 1960s still runs much of the world's banking.",
  "Google's first storage server was built with LEGO bricks.",
  "The 'blue screen of death' has an official name: a bug check, or stop error.",
  "USB was designed to end cable chaos — and gave us three tries to plug it in for 20 years.",
  "The first hard drive to ship (IBM, 1956) stored 5 MB and was moved by forklift.",
  "Linux runs on all of the world's top 500 supercomputers.",
  "The very first banner ad appeared in 1994 — 44% of people who saw it clicked.",
  "Half the world's population was online by roughly 2017 — 25 years after the web went public.",
  "Apple's first product, the Apple I, sold for $666.66.",
  "The C programming language was created in 1972 and still powers most operating systems.",
  "Some early keyboards had no 1 key — typists used lowercase L instead.",
  "The term 'debugging' predates computers — engineers already spoke of bugs in machinery.",
  "Spam is named after the Monty Python sketch, not the canned meat itself.",
  "A modern smartphone has millions of times more computing power than Apollo 11's computer.",
  "The first webcam watched a coffee pot at Cambridge so researchers knew when it was fresh.",
  "The 404 error means 'not found' — folklore ties it to room 404 at CERN, but it's just a code.",
  "Only about 10% of the emoji you use are rendered the same on every platform.",
  "Python the language is named after Monty Python, not the snake.",
  "The average person checks their phone about 100 times a day.",
  "Undersea fiber cables carry over 95% of intercontinental internet traffic.",
  "Moore's law held for 50 years: transistor counts doubled roughly every two years.",
  "The first computer virus for MS-DOS, Brain (1986), included its authors' real address.",
  "Ctrl+Alt+Del was meant as a developer shortcut — it shipped because reboots were handy.",
];
